#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['masstable']

package_data = \
{'': ['*'], 'masstable': ['data/*']}

install_requires = \
['pandas>=1.2.3']

setup(name='masstable',
      version='0.4.1',
      description='Utilities for working with nuclear mass tables',
      author='Yaser Martinez Palenzuela',
      author_email='yaser.martinez@gmail.com',
      url='https://github.com/elyase/masstable',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
