"""
    Veeroute.LSS Field Service Engineers

    Veeroute.LSS Field Service Engineers API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_fieldservice
from vrt_lss_fieldservice.model.cost_penalty import CostPenalty


class TestCostPenalty(unittest.TestCase):
    """CostPenalty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCostPenalty(self):
        """Test CostPenalty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CostPenalty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
