
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T08:35:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "11ac7a18a403af717c0c2a29a33b7cadb75eabd7",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
