[tool.poetry]
name = "garoupa"
version = "1.210410.3"
description = "Cryptographic hash, abstract algebra and operators"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
readme = 'README.md'
packages = [
    { include = "garoupa", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
blake3 = "^0.1.8"
colored = "^1.4.2"
numpy = "^1.20.1"
progress = "^1.5"
pathos = "^0.2.7"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pathos = "^0.2.7"
lange = "^0.2101.24"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
