
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T11:51:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c9367781f9a035e7dd7369b5ff3e52be71b3ca0",
 "version": "1.9.153"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
