[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "nltk>=3.5",
    "numpy==1.19.5",
    "matplotlib==3.4.1",
    "emoji==1.2.0",
    "gensim==4.0.1",
    "sklearn==0.0",
    "tqdm==4.59.0",
    "beautifulsoup4==4.9.3",
    "pandas==1.2.3"
]
build-backend = "setuptools.build_meta"