[tool.poetry]
name = "mockerpy"
version = "0.1.0"
description = "Mock client for Docker-py"
authors = ["Procedural.build <admin@procedural.build>"]
license = "MIT"


[tool.poetry.dependencies]
python = ">=3.6,<3.9"
docker = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
black = "==19.3b0"
pytest-env = "^0.6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.pytest.ini_options]
addopts = "-rspxX -l --tb=short --strict"