
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-18T20:21:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fb23c3f39dd7bc5ba0c0e46b0367caba5d8fc67",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
