
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T22:59:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd6d92ea493cb6ab7fd74f1033209196e0fe9389",
 "version": "0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
