[tool.poetry]
name = "run_once"
version = "0.4.1"
description = ""
authors = ["Daeyun Shin <daeyuns@uci.edu>"]
license = "MIT"
#exclude = ["**"]
include = [
    "run_once.py",
    "generated/proto/*.py",
    "cmake-build-release/distlock",
]

[tool.poetry.scripts]
distlock = "run_once:_run_server"

[tool.poetry.dependencies]
python = "^3.6"
grpcio = "^1.15"
protobuf = "^3.10"
joblib = "^1.0.1"

[tool.poetry.dev-dependencies]
grpcio-tools = "^1.15"
pytest = ">=6"
numpy = ">=1.0"
psutil = "^5"
black = "*"
ipykernel = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
