
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T11:47:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5d85cca560ab1ca09d5dc344293a14103e40799",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
