
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T20:08:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd820e35069e239b987701acfd60f5ed97ec7488",
 "version": "v2.0alpha22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
