[project]
name = "elibs-epython"
version = 2021.1045
description = "Helper library for QA"
authors = [
    "Ray Gomez <codenomad@gmail.com>"
]
license = "MIT"
readme = "README.md"
python = "^3.6"
homepage = "https://github.com/elibs/epython"
repository = "https://github.com/elibs/epython"
documentation = "https://github.com/elibs/epython"

keywords = ["packaging", "dependency", "infer", "pyproject.toml"]

classifiers = [
    "Topic :: Software Development"
]


[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.bumpver]
current_version = "2021.1045"
version_pattern = "YYYY.BUILD"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = {version}',
]
"setup.cfg" = [
    'version = {version}'
]
