FE = [
    {
        "nama": "Ekonomi Pembangunan (S1)",
        "fakultas": "FE",
        "jurusan": "Ekonomi Pembangunan",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/ekonomi-pembangunan-s1/",
    },
    {
        "nama": "Ekonomi Pembangunan (S1) - Ekonomi dan Perbankan Syariah",
        "fakultas": "FE",
        "jurusan": "Ekonomi Pembangunan",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/ekonomi-pembangunan-s1-ekonomi-dan-perbankan-syariah/",
    },
    {
        "nama": "Ekonomi Syariah (S1)",
        "fakultas": "FE",
        "jurusan": "Ekonomi Pembangunan",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/ekonomi-pembangunan-s1-ekonomi-dan-perbankan-syariah/",
    },
    {
        "nama": "Manajemen (S1)",
        "fakultas": "FE",
        "jurusan": "Manajemen",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/manajemen-s1/",
    },
    {
        "nama": "Manajemen (S1) – Manajemen Keuangan dan Perbankan Syariah",
        "fakultas": "FE",
        "jurusan": "Manajemen",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/manajemen-s1-manajemen-keuangan-dan-perbankan-syariah/",
    },
    {
        "nama": "Pariwisata (S1)",
        "fakultas": "FE",
        "jurusan": "Manajemen",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/manajemen-s1-manajemen-keuangan-dan-perbankan-syariah/",
    },
    {
        "nama": "Akuntansi (S1)",
        "fakultas": "FE",
        "jurusan": "Akuntansi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/akuntansi-s1/",
    },
    {
        "nama": "Akuntansi (S1) – Akuntansi Sektor Publik",
        "fakultas": "FE",
        "jurusan": "Akuntansi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/akuntansi-s1-akuntansi-sektor-publik/",
    },
    {
        "nama": "Akuntansi Keuangan Publik (S1)",
        "fakultas": "FE",
        "jurusan": "Akuntansi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fe/akuntansi-keuangan-publik-s1/",
    },
]
