PASCASARJANA = [
    {
        "nama": "Doktor Administrasi Publik (S3)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Doktor",
        "jenjang": "S3",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/doktor-administrasi-publik-s3/",
    },
    {
        "nama": "Doktor Ilmu Manajemen (S3)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Doktor",
        "jenjang": "S3",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/doktor-ilmu-manajemen-s3/",
    },
    {
        "nama": "Magister Ilmu Administrasi (S2) – Administrasi Publik",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-ilmu-administrasi-s2-administrasi-publik/",
    },
    {
        "nama": "Magister Manajemen (S2) – Manajemen Keuangan",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-manajemen-s2-manajemen-keuangan/",
    },
    {
        "nama": "Magister Manajemen (S2) – Manajemen Pemasaran",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-manajemen-s2-manajemen-pemasaran/",
    },
    {
        "nama": "Magister Manajemen (S2) – Manajemen Sumber Daya Manusia",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-manajemen-s2-manajemen-sumber-daya-manusia/",
    },
    {
        "nama": "Magister Ilmu Kelautan (S2) – Manajemen Perikanan",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-ilmu-kelautan-s2-manajemen-perikanan/",
    },
    {
        "nama": "Magister Pendidikan Dasar (S2)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-pendidikan-dasar-s2/",
    },
    {
        "nama": "Magister Pendidikan Matematika (S2)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-pendidikan-matematika-s2/",
    },
    {
        "nama": "Magister Pendidikan Bahasa Inggris (S2)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-pendidikan-bahasa-inggris-s2/",
    },
    {
        "nama": "Magister Studi Lingkungan (S2)",
        "fakultas": "PASCASARJANA",
        "jurusan": "Magister",
        "jenjang": "S2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-studi-lingkungan-s2/",
    },
]
