
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-18T13:33:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "67fc7cda86315586bdc1578813cf2d1f0f77b933",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
