
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T09:48:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c054fe46477c1729e4c57dde788450f718d7bb33",
 "version": "4.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
