[package]
name = "o3iss"
version = "0.1.3"
authors = ["Nikolas Tapia <tapia@wias-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "o3iss"
crate-type = ["cdylib"]

[dependencies]
array2d = "^0.2.1"

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
debug = false
