[tool.poetry]
name = "pdf-redactor"
version = "0.0.1"
description = "A general purpose PDF text-layer redaction tool for Python 2/3"
authors = ["Joshua Tauberer <jt@occams.info>"]
license = "CC0-1.0"

[tool.poetry.dependencies]
python = "^3.7"
pdfrw = ">=0.4"
defusedxml = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
