
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T15:10:42+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "c5df5e87745d7b575463f7b2a0b588e18007dc40",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
