
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-16T10:30:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e27f060782460cc0916c51b0e09a96b883ff67d3",
 "version": "1.9.151"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
