
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T09:55:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a9a6b4bc4f489f6d16fb836931e6f8ba7a861c1",
 "version": "0.7.0.post.dev74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
