
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-16T10:50:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c20443ee8d0d1b3413f63c17ba7676903ca87c5",
 "version": "0.8.3b2.dev202104170706"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
