
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T10:06:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3435c159eacf41f666f3cf489962428d411597ff",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
