[tool.poetry]
name = "rapidbounce-cms"
version = "0.2.0"
description = ""
authors = ["Rapidbounce <customer.support@rapidbounce.co>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
django-storages = {version = "1.9.1", extras = ["google"]}
pillow = "*"
django-ckeditor = "*"
django_compressor = "*"
django-crispy-forms = "*"
django-filer = "*"
django-htmlmin = "*"
django-imagekit = "*"
django-modeltranslation = "*"
django-mptt = "*"
django-mptt-admin = "*"
django-recaptcha = "*"
django-reversion = "*"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
