
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T10:57:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c012f4b79afd7c9606615b85139b9c6ebab2f96d",
 "version": "2438"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
