[tool.poetry]
name = "txt-hours"
version = "0.2.0"
description = ""
authors = ["Andrew Simmons <agsimmons0@gmail.com>"]

[tool.poetry.scripts]
txthours = 'txt_hours:main'

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "1.1.5"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
