
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T17:18:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "391af6f13b305e16522fdd0296cd44eaf8367002",
 "version": "3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
