
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T10:43:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd4eacd85a902406e4e8a43f2f3d0762108841e0",
 "version": "0.7.0.post.dev78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
