[tool.pytest.ini_options]
addopts = "--cov=pynwsradar --cov-report=term-missing"
testpaths = [
	  "tests"
]

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.'MESSAGES CONTROL']
disable=[
	"invalid-name",
        "too-many-instance-attributes",
        "too-many-arguments",
        "too-many-branches",
        "duplicate-code",
	"C0330",
	"C0326"
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
