[tool.poetry]
name = "dotify"
version = "0.1.5"
description = "🐍🎶 Yet another Spotify Web API Python library"
readme = "README.md"
authors = ["billsioros <billsioros97@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-jsonschema-objects = "*"
youtube-search-python = "*"
requests = "*"
moviepy = "*"
spotipy = "*"
mutagen = "*"
pytube = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
pylint = "*"
isort = "*"
pytest = "*"
pytest-cov = "*"
pytest-monkeytype = "*"
monkeytype = "*"
tox = "^3.23.0"
tox-poetry-installer = {extras = ["poetry"], version = "^0.6.4"}
mypy = "^0.812"
black = "^20.8b1"
wemake-python-styleguide = "^0.15.2"
tox-gh-actions = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
