# Generated by Django 3.2 on 2021-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.ManyToManyField(to='Users.EmailNotificationTypesU'),
        ),
    ]
