# Generated by Django 3.2 on 2021-04-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('is_active', models.SmallIntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=16)),
                ('created', models.DateTimeField()),
                ('snapshot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.snapshoot')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshootTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('snapshot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.snapshoot')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=36)),
                ('request_path', models.CharField(max_length=256)),
                ('action_key', models.CharField(max_length=64)),
                ('action_type', models.CharField(max_length=16)),
                ('entity_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('snapshot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.snapshoot')),
            ],
        ),
    ]
