# Generated by Django 3.2 on 2021-04-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_changelog_snapshoot_snapshoottable_snapshotsfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snapshoot',
            new_name='Snapshot',
        ),
        migrations.RenameModel(
            old_name='SnapshootTable',
            new_name='SnapshotTable',
        ),
    ]
