"""
    Veeroute.LSS Delivery

    Veeroute.LSS Delivery API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_delivery
from vrt_lss_delivery.model.tariff_primary import TariffPrimary
globals()['TariffPrimary'] = TariffPrimary
from vrt_lss_delivery.model.tariff import Tariff


class TestTariff(unittest.TestCase):
    """Tariff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTariff(self):
        """Test Tariff"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tariff()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
