"""
    Veeroute.LSS Delivery

    Veeroute.LSS Delivery API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_delivery
from vrt_lss_delivery.model.actualize_settings import ActualizeSettings
from vrt_lss_delivery.model.facts import Facts
from vrt_lss_delivery.model.order import Order
from vrt_lss_delivery.model.performer import Performer
from vrt_lss_delivery.model.trip import Trip
from vrt_lss_delivery.model.warehouse import Warehouse
globals()['ActualizeSettings'] = ActualizeSettings
globals()['Facts'] = Facts
globals()['Order'] = Order
globals()['Performer'] = Performer
globals()['Trip'] = Trip
globals()['Warehouse'] = Warehouse
from vrt_lss_delivery.model.actualize_task import ActualizeTask


class TestActualizeTask(unittest.TestCase):
    """ActualizeTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActualizeTask(self):
        """Test ActualizeTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActualizeTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
