"""
    Veeroute.LSS Delivery

    Veeroute.LSS Delivery API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_delivery
from vrt_lss_delivery.model.actualize_strategy import ActualizeStrategy
globals()['ActualizeStrategy'] = ActualizeStrategy
from vrt_lss_delivery.model.actualize_settings import ActualizeSettings


class TestActualizeSettings(unittest.TestCase):
    """ActualizeSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActualizeSettings(self):
        """Test ActualizeSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActualizeSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
