
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T13:48:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cff6a4612830e511111390a7136733adc97cca13",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
