
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T16:39:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "65b461ce6c1d1868b7183886eaefea6c9075d913",
 "version": "2.5.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
