# Generated by Django 3.2 on 2021-04-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_office', '0002_auto_20210420_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='context',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='max_retries_number',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='retries_number',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='retry_delay',
        ),
    ]
