# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grakn_protocol.common import session_pb2 as common_dot_session__pb2
from grakn_protocol.common import transaction_pb2 as common_dot_transaction__pb2
from grakn_protocol.core import core_database_pb2 as core_dot_core__database__pb2


class GraknCoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.databases_contains = channel.unary_unary(
        '/grakn.protocol.GraknCore/databases_contains',
        request_serializer=core_dot_core__database__pb2.CoreDatabaseManager.Contains.Req.SerializeToString,
        response_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.Contains.Res.FromString,
        )
    self.databases_create = channel.unary_unary(
        '/grakn.protocol.GraknCore/databases_create',
        request_serializer=core_dot_core__database__pb2.CoreDatabaseManager.Create.Req.SerializeToString,
        response_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.Create.Res.FromString,
        )
    self.databases_all = channel.unary_unary(
        '/grakn.protocol.GraknCore/databases_all',
        request_serializer=core_dot_core__database__pb2.CoreDatabaseManager.All.Req.SerializeToString,
        response_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.All.Res.FromString,
        )
    self.database_schema = channel.unary_unary(
        '/grakn.protocol.GraknCore/database_schema',
        request_serializer=core_dot_core__database__pb2.CoreDatabase.Schema.Req.SerializeToString,
        response_deserializer=core_dot_core__database__pb2.CoreDatabase.Schema.Res.FromString,
        )
    self.database_delete = channel.unary_unary(
        '/grakn.protocol.GraknCore/database_delete',
        request_serializer=core_dot_core__database__pb2.CoreDatabase.Delete.Req.SerializeToString,
        response_deserializer=core_dot_core__database__pb2.CoreDatabase.Delete.Res.FromString,
        )
    self.session_open = channel.unary_unary(
        '/grakn.protocol.GraknCore/session_open',
        request_serializer=common_dot_session__pb2.Session.Open.Req.SerializeToString,
        response_deserializer=common_dot_session__pb2.Session.Open.Res.FromString,
        )
    self.session_close = channel.unary_unary(
        '/grakn.protocol.GraknCore/session_close',
        request_serializer=common_dot_session__pb2.Session.Close.Req.SerializeToString,
        response_deserializer=common_dot_session__pb2.Session.Close.Res.FromString,
        )
    self.session_pulse = channel.unary_unary(
        '/grakn.protocol.GraknCore/session_pulse',
        request_serializer=common_dot_session__pb2.Session.Pulse.Req.SerializeToString,
        response_deserializer=common_dot_session__pb2.Session.Pulse.Res.FromString,
        )
    self.transaction = channel.stream_stream(
        '/grakn.protocol.GraknCore/transaction',
        request_serializer=common_dot_transaction__pb2.Transaction.Client.SerializeToString,
        response_deserializer=common_dot_transaction__pb2.Transaction.Server.FromString,
        )


class GraknCoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def databases_contains(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def databases_create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def databases_all(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def database_schema(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def database_delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def session_open(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def session_close(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def session_pulse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def transaction(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GraknCoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'databases_contains': grpc.unary_unary_rpc_method_handler(
          servicer.databases_contains,
          request_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.Contains.Req.FromString,
          response_serializer=core_dot_core__database__pb2.CoreDatabaseManager.Contains.Res.SerializeToString,
      ),
      'databases_create': grpc.unary_unary_rpc_method_handler(
          servicer.databases_create,
          request_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.Create.Req.FromString,
          response_serializer=core_dot_core__database__pb2.CoreDatabaseManager.Create.Res.SerializeToString,
      ),
      'databases_all': grpc.unary_unary_rpc_method_handler(
          servicer.databases_all,
          request_deserializer=core_dot_core__database__pb2.CoreDatabaseManager.All.Req.FromString,
          response_serializer=core_dot_core__database__pb2.CoreDatabaseManager.All.Res.SerializeToString,
      ),
      'database_schema': grpc.unary_unary_rpc_method_handler(
          servicer.database_schema,
          request_deserializer=core_dot_core__database__pb2.CoreDatabase.Schema.Req.FromString,
          response_serializer=core_dot_core__database__pb2.CoreDatabase.Schema.Res.SerializeToString,
      ),
      'database_delete': grpc.unary_unary_rpc_method_handler(
          servicer.database_delete,
          request_deserializer=core_dot_core__database__pb2.CoreDatabase.Delete.Req.FromString,
          response_serializer=core_dot_core__database__pb2.CoreDatabase.Delete.Res.SerializeToString,
      ),
      'session_open': grpc.unary_unary_rpc_method_handler(
          servicer.session_open,
          request_deserializer=common_dot_session__pb2.Session.Open.Req.FromString,
          response_serializer=common_dot_session__pb2.Session.Open.Res.SerializeToString,
      ),
      'session_close': grpc.unary_unary_rpc_method_handler(
          servicer.session_close,
          request_deserializer=common_dot_session__pb2.Session.Close.Req.FromString,
          response_serializer=common_dot_session__pb2.Session.Close.Res.SerializeToString,
      ),
      'session_pulse': grpc.unary_unary_rpc_method_handler(
          servicer.session_pulse,
          request_deserializer=common_dot_session__pb2.Session.Pulse.Req.FromString,
          response_serializer=common_dot_session__pb2.Session.Pulse.Res.SerializeToString,
      ),
      'transaction': grpc.stream_stream_rpc_method_handler(
          servicer.transaction,
          request_deserializer=common_dot_transaction__pb2.Transaction.Client.FromString,
          response_serializer=common_dot_transaction__pb2.Transaction.Server.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grakn.protocol.GraknCore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
