
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-17T18:06:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "311da3b307576f7f22256dccd06f162ed8d6e3dd",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
