
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T00:20:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1177e4180b5e8df96a85bfed25d1d98510cb141",
 "version": "1.0.0.post.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
