
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T17:50:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "845170d05b63ae7a26062d94f33bdecb97ed98ce",
 "version": "v0.17a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
