
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T13:00:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d3b6ea6ee6be8a4ac56744df61ca0a9292d13a4",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
