
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T10:31:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "14a396b29ec3f13c4d727c0126906ab850ab2aed",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
