
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T09:40:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcc4d75a4d2c6aaa7e50e75095a16df1df6b2b0a",
 "version": "v1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
