
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T13:50:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe10f13dae4d0b3380dbb0178bceaac10c3a743c",
 "version": "2021.04.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
