
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T13:13:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e16f1a18132e37f7d9f0330325def85d8615a64d",
 "version": "1.0.4rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
