
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T20:37:46+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "a14633895b40d4a6cfbe1385e834c469be08aa34",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
