prune_ratios:
#  module_list.0.Conv2d.weight:
#    0.0
  module_list.1.Conv2d.weight:
    0.4
  module_list.2.Conv2d.weight:
    0.5
  module_list.3.Conv2d.weight:
    0.4
  module_list.5.Conv2d.weight:
    0.6
  module_list.6.Conv2d.weight:
    0.5
  module_list.8.Conv2d.weight:
    0.6
  module_list.9.Conv2d.weight:
    0.4
  module_list.10.Conv2d.weight:
    0.5
  module_list.12.Conv2d.weight:
    0.5
  module_list.13.Conv2d.weight:
    0.7
  module_list.15.Conv2d.weight:
    0.5
  module_list.17.Conv2d.weight:
    0.7
  module_list.18.Conv2d.weight:
    0.85
  module_list.19.Conv2d.weight:
    0.85
  module_list.21.Conv2d.weight:
    0.92
  module_list.22.Conv2d.weight:
    0.7
  module_list.23.Conv2d.weight:
    0.85
  module_list.25.Conv2d.weight:
    0.7
  module_list.26.Conv2d.weight:
    0.92
  module_list.28.Conv2d.weight:
    0.7
  module_list.29.Conv2d.weight:
    0.92
  module_list.31.Conv2d.weight:
    0.7
  module_list.32.Conv2d.weight:
    0.92
  module_list.34.Conv2d.weight:
    0.7
  module_list.35.Conv2d.weight:
    0.92
  module_list.37.Conv2d.weight:
    0.7
  module_list.38.Conv2d.weight:
    0.92
  module_list.40.Conv2d.weight:
    0.7
  module_list.41.Conv2d.weight:
    0.92
  module_list.43.Conv2d.weight:
    0.7
  module_list.44.Conv2d.weight:
    0.92
  module_list.46.Conv2d.weight:
    0.7
  module_list.48.Conv2d.weight:
    0.8
  module_list.49.Conv2d.weight:
    0.92
  module_list.50.Conv2d.weight:
    0.8
  module_list.52.Conv2d.weight:
    0.8
  module_list.53.Conv2d.weight:
    0.7
  module_list.54.Conv2d.weight:
    0.8
  module_list.56.Conv2d.weight:
    0.7
  module_list.57.Conv2d.weight:
    0.92
  module_list.59.Conv2d.weight:
    0.7
  module_list.60.Conv2d.weight:
    0.92
  module_list.62.Conv2d.weight:
    0.7
  module_list.63.Conv2d.weight:
    0.92
  module_list.65.Conv2d.weight:
    0.7
  module_list.66.Conv2d.weight:
    0.92
  module_list.68.Conv2d.weight:
    0.8
  module_list.69.Conv2d.weight:
    0.92
  module_list.71.Conv2d.weight:
    0.7
  module_list.72.Conv2d.weight:
    0.92
  module_list.74.Conv2d.weight:
    0.7
  module_list.75.Conv2d.weight:
    0.85
  module_list.77.Conv2d.weight:
    0.7
  module_list.79.Conv2d.weight:
    0.8
  module_list.80.Conv2d.weight:
    0.92
  module_list.81.Conv2d.weight:
    0.8
  module_list.83.Conv2d.weight:
    0.85
  module_list.84.Conv2d.weight:
    0.8
  module_list.85.Conv2d.weight:
    0.92
  module_list.87.Conv2d.weight:
    0.8
  module_list.88.Conv2d.weight:
    0.92
  module_list.90.Conv2d.weight:
    0.8
  module_list.91.Conv2d.weight:
    0.92
  module_list.93.Conv2d.weight:
    0.8
  module_list.94.Conv2d.weight:
    0.92
  module_list.96.Conv2d.weight:
    0.7
  module_list.98.Conv2d.weight:
    0.8
  module_list.99.Conv2d.weight:
    0.8
  module_list.100.Conv2d.weight:
    0.92
  module_list.101.Conv2d.weight:
    0.85
  module_list.108.Conv2d.weight:
    0.85
  module_list.109.Conv2d.weight:
    0.95
  module_list.110.Conv2d.weight:
    0.8
  module_list.111.Conv2d.weight:
    0.7
  module_list.114.Conv2d.weight:
    0.7
  module_list.116.Conv2d.weight:
    0.7
  module_list.117.Conv2d.weight:
    0.95
  module_list.118.Conv2d.weight:
    0.7
  module_list.119.Conv2d.weight:
    0.95
  module_list.120.Conv2d.weight:
    0.8
  module_list.121.Conv2d.weight:
    0.7
  module_list.124.Conv2d.weight:
    0.7
  module_list.126.Conv2d.weight:
    0.7
  module_list.127.Conv2d.weight:
    0.95
  module_list.128.Conv2d.weight:
    0.7
  module_list.129.Conv2d.weight:
    0.95
  module_list.130.Conv2d.weight:
    0.7
  module_list.131.Conv2d.weight:
    0.85
#  module_list.132.Conv2d.weight:
#    0.85
  module_list.135.Conv2d.weight:
    0.85
  module_list.137.Conv2d.weight:
    0.8
  module_list.138.Conv2d.weight:
    0.95
  module_list.139.Conv2d.weight:
    0.8
  module_list.140.Conv2d.weight:
    0.95
  module_list.141.Conv2d.weight:
    0.8
  module_list.142.Conv2d.weight:
    0.92
#  module_list.143.Conv2d.weight:
#    0.8
  module_list.146.Conv2d.weight:
    0.85
  module_list.148.Conv2d.weight:
    0.85
  module_list.149.Conv2d.weight:
    0.85
  module_list.150.Conv2d.weight:
    0.8
  module_list.151.Conv2d.weight:
    0.85
  module_list.152.Conv2d.weight:
    0.92
  module_list.153.Conv2d.weight:
    0.8
#  module_list.154.Conv2d.weight:
#    0.8


