
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T17:09:56+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "316c1b60ca7824cec03f022d2fb799fda2bc1248",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
