#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['vulnerabilities',
 'vulnerabilities.tools.bandit',
 'vulnerabilities.tools.cyclonedx',
 'vulnerabilities.tools.semgrep']

package_data = \
{'': ['*'], 'vulnerabilities': ['tools/*']}

install_requires = \
['python-dateutil', 'cvss', 'defusedxml']

setup(name='vulnerabilities',
      version='0.0.2',
      description='Module to manage vulnerabilities',
      author='Damien Carol',
      author_email='damien.carol@gmail.com',
      url='https://github.com/damiencarol/vulnerabilities',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
