
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T06:03:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "20d7538477b2af538c82584e0f877116d8a35bcf",
 "version": "v1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
