
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T19:03:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "473890c8a33ee45b55201bcf70c2d72fbe43e74a",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
