
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T17:01:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ad438a80075b6e9184b7a7a8c8ea83ac5c2c764",
 "version": "0.4.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
