
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T01:05:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d72dedc40fd3650b260a4573721ff2ab0f5dd457",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
