
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T22:07:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3a9fb49d1e4a38d4dd050cdcd174636d33295bc",
 "version": "2.6.0-alpha.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
