
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-16T11:52:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6579ddd22e306a1b048fc5247b844e39c13783e3",
 "version": "v1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
