[tool.portray]
docs_dir="documentation\\Markdown"
modules=[
    "fastrlapi.agents",
    "fastrlapi.env",
    "fastrlapi.core",
    "fastrlapi.backends.core",
    "fastrlapi.backends.tfagents",
    "fastrlapi.callbacks.duration",
    "fastrlapi.callbacks.log",
    "fastrlapi.callbacks.plot",
    "fastrlapi.callbacks.save",
    ]




