
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T11:24:22+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7efa62f2a5e4fa8df1cb53cf01ea29fbd004c5ca",
 "version": "0.6.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
