[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pyshs"
author = "Émilien Schultz"
author-email = "emilien.schultz@gmail.com"
home-page = "http://eschultz.fr"
classifiers = [ "License :: OSI Approved :: MIT License",]
requires=["pandas",
          "numpy",
          "scipy"]
