#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['pandas', 'numpy', 'scipy']

setup(name='pyshs',
      version='0.1.0',
      description='Module PySHS pour faciliter le traitement statistique en SHS avec Python',
      author='Émilien Schultz',
      author_email='emilien.schultz@gmail.com',
      url='http://eschultz.fr',
      py_modules=['pyshs'],
      install_requires=install_requires,
     )
