
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T12:17:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f2d074cce12646dd93d81d7d322f2d2ecb0d273",
 "version": "0.4.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
