
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T18:09:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b857934a944b83a151c8159393be5e075e63d9c",
 "version": "v1.2.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
