
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T13:41:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c46c077a40cde5ff5e7b01b5874e0ef8ca050f09",
 "version": "1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
