[tool.poetry]
name = "overrides_extension"
version = "3.2.3"
description = "A decorator to automatically detect mismatch when overriding a method."
license = "Apache License, Version 2.0"
authors = ["Mikko Korpela <mikko.korpela@gmail.com>", "Eugene Mozharovsky <mozharovsky@live.com>"]

readme = "README.rst"
repository = "https://github.com/mozharovsky/overrides"
keywords = ["override", "inheritence", "OOP"]

classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]

include = ["LICENSE", "README.rst", "tox.ini", "tests/*.py"]

[tool.poetry.dependencies]
python = ">=3.6.0,<3.10.0"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
