[tool.poetry]
name = "udft"
version = "2.0.0"
description = "Unitary discrete Fourier Transform (and related)"
authors = ["François Orieux <francois.orieux@universite-paris-saclay.fr>"]
maintainers = ["François Orieux <francois.orieux@universite-paris-saclay.fr>"]
readme = "README.md"
license = "WTFPL"
homepage = "https://github.com/forieux/udft/"
documentation = "https://qmm.readthedocs.io/en/stable/"
repository = "https://github.com/forieux/udft/"
keywords = ["fft", "orthonormal"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/forieux/udft/issues"
"Author webpage" = "https://pro.orieux.fr/"

[tool.poetry.dependencies]
python = "^3.7, <4.0"
numpy = "^1.20.2"
pyFFTW = {version = "^0.12.0", optional = true}

[tool.poetry.dev-dependencies]
ipython = "^7.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

