
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T19:21:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "467c1bdb4309ca2728b0b3a09afee759e418c272",
 "version": "v1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
