[tool.poetry]
name = "formerbox"
version = "0.3.0b2"
description = ""
authors = ["mozharovsky <mozharovsky@live.com>"]

[tool.poetry.scripts]
formerbox-cli = 'formerbox.__main__:run_main'

[tool.poetry.dependencies]
# Deep learning toolkit
python = ">=3.7.4,<3.10.0"
torch = ">=1.8.0,<1.9.0"
pytorch-lightning = ">=1.2.0,<1.3.0"

# NLP toolkit packages
transformers = ">=4.5.0,<4.6.0"
datasets = ">=1.5.0,<1.6.0"
sacrebleu = "^1.5.1"
sentencepiece = "^0.1.95"

# Machine learning toolkit
numpy = "^1.20.2"
pandas = "^1.2.4"
scikit-learn = "^0.24.1"
scipy = "^1.6.2"

# Misc toolkit packages
tqdm = "^4.40.0"
matplotlib = "^3.4.1"
wandb = "^0.10.26"
boto3 = "^1.17.53"

# System programming toolkit
pydriller = "^1.15.5"
tree_sitter = "^0.19.0"

# Python types magic and extensions
typing_inspect = "^0.6.0"
typing-extensions = "^3.7.4"
types-typing-extensions = "^3.7.3"
overrides_extension = "^3.2.0"
more-itertools = "^8.7.0"
jsonlines = "^2.0.0"
traitlets = "^4.3.3"
PyYAML = "^5.1.0"

# Conditionally installed for backward compatibility with older Python versions
dataclasses = { version = "^0.8", python = "^3.6,<3.7" }

# Optional dependencies
sphinx = { version = "^3.5.4", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }
rstcheck = { version = "^3.3.1", optional = true }

[tool.poetry.dev-dependencies]
pylint = "^2.7.4"
black = "^20.8b1"
jupyter = "^1.0.0"
jupyterlab = "^3.0.14"
commitizen = "^2.17.2"
cookiecutter = "^1.7.2"
pytest = "^6.2.3"
pytest-ordering = "^0.6"

[tool.commitizen]
name = "cz_formerbox"
version = "0.1.0"
tag_format = "$version"

[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
