dist: xenial
services:
  - docker
cache:
  directories:
    - ${HOME}/.cache
    - ${HOME}/cached-deps
    - ${HOME}/gopath/pkg/mod
    - "$(python3 -c 'import site; print(site.USER_BASE)')"
language: python
python:
  - "3.9"
  - "3.5"
env:
  global:
    - PATH=$HOME/cached-deps:$PATH
  jobs:
    - PACHYDERM_VERSION=2.0.0-alpha.12

jobs:
  include:
    # other tests
    - python: 3.8
      env:
        - TOXENV=lint
        - PACHYDERM_VERSION=2.0.0-alpha.12
    - python: 3.8
      env:
        - TOXENV=examples
        - PACHYDERM_VERSION=2.0.0-alpha.12
install:
- make ci-install
before_script:
- make ci-setup
script:
- tox
after_script:
- kubectl describe pods
- kubectl logs --previous deployment/pachd

before_cache:
  # Make sure cache dirs have the necessary permissions for Travis to traverse
  # & copy them all elsewhere
  - proto/pachyderm/etc/testing/travis_cache.sh
