#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['faker_airtravel', 'faker_airtravel.airtravel']

package_data = \
{'': ['*'], 'faker_airtravel.airtravel': ['tests/*']}

setup(name='faker_airtravel',
      version='0.1',
      description='AirTravel Faker Community Provider',
      author='David Kotschessa',
      author_email='itzdavey@gmail.com',
      url='https://github.com/dkotschessa/faker_airtravel.git',
      packages=packages,
      package_data=package_data,
     )
