
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T13:57:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ed89b6cb9e8c8336b6bd82e5c6f2d1b13276f87",
 "version": "2439"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
