
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T18:21:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "92a61c1bf254364bf2a86f88363070a7de6aad24",
 "version": "0.0.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
