# -*- coding: utf-8 -*-

"""
    signing

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from signing.decorators import lazy_property
from signing.configuration import Configuration
from signing.controllers.misc_controller import MiscController


class SigningClient(object):

    config = Configuration

    @lazy_property
    def misc(self):
        return MiscController()


