"""
    Veeroute.LSS Studio

    LSS Studio Tool API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_studio
from vrt_lss_studio.model.method_statistics import MethodStatistics
from vrt_lss_studio.model.service_name import ServiceName
globals()['MethodStatistics'] = MethodStatistics
globals()['ServiceName'] = ServiceName
from vrt_lss_studio.model.service_statistics import ServiceStatistics


class TestServiceStatistics(unittest.TestCase):
    """ServiceStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceStatistics(self):
        """Test ServiceStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
