"""
    Veeroute.LSS Studio

    LSS Studio Tool API  # noqa: E501

    The version of the OpenAPI document: 3.8.168672
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vrt_lss_studio
from vrt_lss_studio.model.date_window import DateWindow


class TestDateWindow(unittest.TestCase):
    """DateWindow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDateWindow(self):
        """Test DateWindow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DateWindow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
