[tool.poetry]
name = "lyono"
version = "1.1.0"
description = ""
authors = ["Kevin Hill <kah.kevin.hill@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.5.3"
pydantic = "^1.7.3"
datamodel-code-generator = "^0.6.10"
genson = "^1.2.2"
auto-all = "^1.3.0"
orjson = "^3.4.6"
httpx = "^0.17.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
flake8 = "^3.8.4"
yapf = "^0.30.0"
pylint = "^2.6.0"
autopep8 = "^1.5.4"
rope = "^0.18.0"
pytest-mock = "^3.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
