
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T22:52:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a47dc0c24500ba950c325978a0b6c8e7ecf663d",
 "version": "4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
