[tool.poetry]
name = "data-engineering-pulumi-components"
version = "0.1.0.dev1"
description = "Reusable components for use in Pulumi Python projects"
authors = ["MoJ Data Engineering Team <data-engineering@digital.justice.gov.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pulumi = "^2.20.0"
pulumi-aws = "^3.29.0"
boto3 = "^1.17.50"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
pytest = "^6.2.2"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
