[tool.poetry]
name = "data_grid_surface"
version = "1.2.0"
description = "SDK to communicate with data-grid API"
authors = ["DataGrid Dev Team <dev@datagridsurface.com>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
keywords = ["data", "grid", "surface", "breach"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
include = [
    "LICENSE",
]
packages = [
    { include = "data_grid_surface" },
    { include = "config", from = "data_grid_surface" }
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
python-dotenv = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
