[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "telemuninn"
author = "Namuan"
author-email = "me@deskriders.dev"
home-page = "https://github.com/namuan/tele-muninn"
requires-python = ">=3.7"
description-file = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[tool.flit.scripts]
telemunin = "telemuninn:__main__.main"

[tool.black]
line-length = 100