
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T18:02:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbae4654fb7282df6cc0db90aef00b718ae7478a",
 "version": "0.0.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
