
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T05:36:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a9463a9296c91aad630e542ca28939de3fac473",
 "version": "0.7.0.post.dev70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
