# David Walshe
# 07-Apr-2021
#
# Logger configuration

version: 1
disable_existing_loggers: false

formatters:
  console:
    (): sla_cli.src.common.logger.formatter.ColorFormatter
#    format: "%(levelname)-8s - %(message)s"
  file:
    format: "%(asctime)s - %(levelname)-8s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout

#  file:
#    class: logging.handlers.RotatingFileHandler
#    level: INFO
#    formatter: file
#    filename: .sla_cli.log
#    maxBytes: 10486760
#    backupCount: 20
#    encoding: utf8
#    mode: w

root:
  level: NOTSET
  # Add "file" to list to enable file logging if needed.
  handlers: [console]
  propogate: yes