# THEMES
WGL_THEME_DEFAULT = "╚╔╩╦╠═╬╝╗║╣"
WGL_THEME_THIN = "└┌┴┬├─┼┘┐│┤"
WGL_THEME_SIMPLISTIC = "+++++-+++|+"
WGL_THEME_BLOCKY = "███████████"

# TEXTBOX TYPES
WGL_TYPES_STRING = "WGL_TYPES_STRING"
WGL_TYPES_INT = "WGL_TYPES_INT"
WGL_TYPES_FLOAT = "WGL_TYPES_FLOAT"
