# -*- coding: utf-8 -*-

"""
    signing

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from signing.api_helper import APIHelper


class MiscControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(MiscControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.misc

    # Todo: Add description for test test_get_users
    def test_get_users(self):
        # Parameters for the API call
        email = 'testing@testing.com'

        # Perform the API call through the SDK function
        self.controller.get_users(email)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_login
    def test_login(self):
        # Parameters for the API call
        content_type = 'application/json'
        username = '+966555555555'
        password = 'password'
        client_id = '773ceb43ce4346bfa85271d2bf53d262'
        client_secret = 'CmKeWZa_jA_bv8yL-zePBx2endrl1O9MKY3-eU05y9w'
        grant_type = 'password'
        scope = 'users:read'

        # Perform the API call through the SDK function
        self.controller.login(content_type, username, password, client_id, client_secret, grant_type, scope)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

