
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T12:32:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b1d2543e1977fb07e43487f257c95a693e43303",
 "version": "0.7.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
