
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T07:47:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fc95bc423594dc6f1e32fdca66804ccda818a7a",
 "version": "2.5.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
