[tool.poetry]
name = "tap-hubspot-meister"
version = "0.1.1"
description = ""
authors = ["Juan Sebastian Suarez Valencia <juan.valencia@meisterlabs.com>"]

[tool.poetry.dependencies]
python = "^3.7"
singer-python = "^5.12.1"
hubspot-api-client = "^3.7.2"
pydash = "^5.0.0"
rich = "^10.1.0"
singer = "^0.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tap_hubspot_meister="tap_hubspot_meister.__init__:main"