# Generated by Django 3.2 on 2021-04-15 17:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('rapidbounce_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='url_el',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardimage',
            name='image_el',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='awardimage',
            name='image_en',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='address_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='address_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='country_el',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='country_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='location_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='location_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='description_el',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='small_title_el',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='small_title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='alt_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='alt_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='caption_big_el',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='caption_big_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='caption_small_el',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='caption_small_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='title_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='external_url_el',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='external_url_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='extra_menu_el',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='extra_menu_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='friendlyurl_el',
            field=models.SlugField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='friendlyurl_en',
            field=models.SlugField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='description_el',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='title_el',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='url_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialtags',
            name='description_el',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='socialtags',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='socialtags',
            name='title_el',
            field=models.CharField(default='', max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='socialtags',
            name='title_en',
            field=models.CharField(default='', max_length=95, null=True),
        ),
    ]
