
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T17:11:08-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e6afbc0a4a3cad884f4158f7b8f76184f7e5b06",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
