
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T07:59:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3443f91f758014615e288a5d968473070dc417bf",
 "version": "0.7.0.post.dev72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
