
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-18T16:45:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "da43570ca2f5732b536d9e8193e39b3c9981a9cc",
 "version": "0.8.3b3.dev202104190706"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
