
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-19T08:57:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3e274fdce67d31bbdcbba8fb3ad812d57bc4adb",
 "version": "2442"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
