
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-14T09:56:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "33724b955db0cfd10462484fe48f1ab0df7aabd5",
 "version": "0.14.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
