
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-15T14:50:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "031b93566306e0ce3c0f3aafaed7bb30648e5693",
 "version": "4.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
