[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "domdf_sphinx_theme"
version = "21.1.0"
description = "Customised 'sphinx_rtd_theme' used by my Python projects."
readme = "README.rst"
keywords = [ "sphinx", "sphinx-theme", "documentation",]
dynamic = []
dependencies = [ "docutils>=0.16", "sphinx>=3.0.3", "sphinx-rtd-theme<0.5",]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Extension",
    "Framework :: Sphinx :: Theme",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: JavaScript",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
requires-python = ">=3.6"

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/domdf_sphinx_theme"
"Issue Tracker" = "https://github.com/domdfcoding/domdf_sphinx_theme/issues"
"Source Code" = "https://github.com/domdfcoding/domdf_sphinx_theme"
Documentation = "https://domdf_sphinx_theme.readthedocs.io/en/latest"

[tool.importcheck]
always = [ "domdf_sphinx_theme",]

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Extension",
    "Framework :: Sphinx :: Theme",
    "Intended Audience :: Developers",
    "Programming Language :: JavaScript",
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"
additional-files = [
    "recursive-include domdf_sphinx_theme css/*.css",
    "recursive-include domdf_sphinx_theme js/*.js",
    "recursive-include domdf_sphinx_theme *.html",
    "include domdf_sphinx_theme/theme.conf",
]

[tool.mkrecipe]
conda-channels = [ "domdfcoding",]
extras = "all"

[project.entry-points."sphinx.html_themes"]
domdf_sphinx_theme = "domdf_sphinx_theme"
