#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['telemuninn']

package_data = \
{'': ['*']}

setup(name='telemuninn',
      version='0.1.2',
      description="Let's find some podcasts!",
      author='Namuan',
      author_email='me@deskriders.dev',
      url='https://github.com/namuan/tele-muninn',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
