
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-20T15:59:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebdbc803560e6c6b9208a2485b0d973b70b7c902",
 "version": "1.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
