""" Tablib. """
try:
    # Generated by setuptools-scm.
    from ._version import version as __version__
except ImportError:
    # Some broken installation.
    __version__ = None


from .core import (
    DialogManager, InMemoryDialog,
    InMemoryDataStore, InMemoryDialogSet
)
