# Generated by Django 2.2.16 on 2020-09-12 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("user_feedback", "0001_initial"),
        ("user_feedback", "0002_auto_20191219_2043"),
        ("user_feedback", "0003_auto_20191220_1906"),
        ("user_feedback", "0004_auto_20200219_2143"),
        ("user_feedback", "0005_auto_20200909_1528"),
        ("user_feedback", "0006_remove_feedback_rating"),
        ("user_feedback", "0007_auto_20200912_2200"),
        ("user_feedback", "0008_auto_20200912_2230"),
        ("user_feedback", "0009_auto_20200912_2236"),
    ]

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(default="null", max_length=2000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Bug Report"),
                            (2, "Feature Request"),
                            (3, "General Feedback"),
                        ]
                    ),
                ),
                ("url", models.CharField(max_length=200)),
            ],
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedback"},
        )
    ]
