# Generated by Django 2.2.16 on 2020-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user_feedback", "0001_squashed_0009_auto_20200912_2236")]

    operations = [
        migrations.AlterField(
            model_name="feedback", name="text", field=models.CharField(max_length=2000)
        )
    ]
