#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pikta_calendar']

package_data = \
{'': ['*']}

setup(name='pikta_calendar',
      version='0.1.0',
      description='Production calendar from www.consultant.ru',
      author='Aleksandr Egorov',
      author_email='stigsanek@yandex.ru',
      url='https://github.com/stigsanek/pikta-calendar',
      packages=packages,
      package_data=package_data,
     )
