[build-system]
requires = ["flit_core >=3.2.0,<3.3"]
build-backend = "flit_core.buildapi"

[project]
name = "hydromt"
authors = [
    {name = "Dirk Eilander", email = "dirk.eilander@deltares.nl"},
    {name = "Hélène Boisgontier", email = "helene.boisgontier@deltares.nl"},
]
dependencies = [
    "affine",
    "bottleneck",
    "click",
    "dask",
    "geopandas>=0.8",
    "entrypoints",
    "numpy",
    "pandas",
    "pyflwdir>=0.4.5",
    "pygeos",
    "openpyxl",
    "rasterio",
    "requests",
    "scipy",
    "xarray",
    "zarr",

]
requires-python = ">=3.8" # fix tests to support older versions
readme = "README.rst"
classifiers = [
    # https://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Hydrology",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ['version', 'description']

[project.optional-dependencies]
test = [
	"testpath",
	"responses",
	"pytest>=2.7.3",
	"pytest-cov",
]
doc = [
	"sphinx",
	"sphinx_rtd_theme",
	"black",
]

[project.urls]
Documentation = "https://hydromt.readthedocs.io"
Source = "https://github.com/Deltares/hydromt"

[project.scripts]
hydromt = "hydromt.cli.main:main"

[tool.black]
line-length = 88
target-version = ['py37']