FHISIP = [
    {
        "nama": "Perpajakan (D-III)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Administrasi",
        "jenjang": "D3",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/perpajakan-d3/",
    },
    {
        "nama": "Ilmu Administrasi Negara (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Administrasi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-administrasi-negara-s1/",
    },
    {
        "nama": "Ilmu Administrasi Negara (S1) – Administrasi dan Manajemen Kepegawaian",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Administrasi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-administrasi-negara-s1-administrasi-dan-manajemen-kepegawaian/",
    },
    {
        "nama": "Ilmu Administrasi Bisnis (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Administrasi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-administrasi-bisnis-s1/",
    },
    {
        "nama": "Ilmu Pemerintahan (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Administrasi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-pemerintahan-s1/",
    },
    {
        "nama": "Kearsipan (D-IV)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Komunikasi dan Informasi",
        "jenjang": "D4",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/kearsipan-d4/",
    },
    {
        "nama": "Ilmu Komunikasi (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Komunikasi dan Informasi",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-komunikasi-s1/",
    },
    {
        "nama": "Perpustakaan (D-II)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Komunikasi dan Informasi",
        "jenjang": "D2",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/perpustakaan-d2/",
    },
    {
        "nama": "Sosiologi (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Sosial, Hukum, dan Humaniora",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/sosiologi-s1/",
    },
    {
        "nama": "Ilmu Hukum (S1)",
        "fakultas": "FHISIP",
        "jurusan": "Ilmu Sosial, Hukum, dan Humaniora",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fhisip/ilmu-hukum-s1/",
    },
]
