FKIP = [
    {
        "nama": "Pendidikan Bahasa dan Sastra Indonesia (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Bahasa dan Seni",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-bahasa-dan-sastra-indonesia-s1/",
    },
    {
        "nama": "Pendidikan Bahasa Inggris (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Bahasa dan Seni",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-bahasa-inggris-s1/",
    },
    {
        "nama": "Pendidikan Biologi (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Matematika dan Ilmu Pengetahuan Alam",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-biologi-s1/",
    },
    {
        "nama": "Pendidikan Matematika (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Matematika dan Ilmu Pengetahuan Alam",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-matematika-s1/",
    },
    {
        "nama": "Pendidikan Pancasila dan Kewarganegaraan (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Ilmu Pengetahuan Sosial",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-pancasila-dan-kewarganegaraan-s1/",
    },
    {
        "nama": "Pendidikan Ekonomi (S1)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Ilmu Pengetahuan Sosial",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-ekonomi-s1/",
    },
    {
        "nama": "Teknologi Pendidikan (S1)",
        "fakultas": "FKIP",
        "jurusan": "Teknologi Pendidikan",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/teknologi-pendidikan-s1/",
    },
    {
        "nama": "Pendidikan Guru Pendidikan Anak Usia Dini (S1-PGPAUD)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Dasar",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-guru-pendidikan-anak-usia-dini-s1-pgpaud/",
    },
    {
        "nama": "Pendidikan Guru Sekolah Dasar (S1-PGSD)",
        "fakultas": "FKIP",
        "jurusan": "Pendidikan Dasar",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/pendidikan-guru-sekolah-dasar-s1-pgsd/",
    },
    {
        "nama": "Program Sertifikat",
        "fakultas": "FKIP",
        "jurusan": "Sertifikat",
        "jenjang": "Sertifikat",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fkip/program-sertifikat/",
    },
]
