FST = [
    {
        "nama": "Matematika (S1)",
        "fakultas": "FST",
        "jurusan": "Matematika dan Ilmu Pengetahuan Alam",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/matematika-s1/",
    },
    {
        "nama": "Statistika (S1)",
        "fakultas": "FST",
        "jurusan": "Matematika dan Ilmu Pengetahuan Alam",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/statistika-s1/",
    },
    {
        "nama": "Biologi (S1)",
        "fakultas": "FST",
        "jurusan": "Matematika dan Ilmu Pengetahuan Alam",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/pascasarjana/magister-manajemen-s2-manajemen-pemasaran/",
    },
    {
        "nama": "Perencanaan Wilayah dan Kota (S1)",
        "fakultas": "FST",
        "jurusan": "Teknik",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/perencanaan-wilayah-dan-kota-s1-pengelolaan-sumber-daya-alam-dan-lingkunga/",
    },
    {
        "nama": "Sistem Informasi (S1)",
        "fakultas": "FST",
        "jurusan": "Teknik",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/sistem-informasi-s1/",
    },
    {
        "nama": "Agribisnis (S1) - Penyuluhan dan Komunikasi Pertanian",
        "fakultas": "FST",
        "jurusan": "Pertanian",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/agribisnis-s1-penyuluhan-dan-komunikasi-pertanian/",
    },
    {
        "nama": "Agribisnis (S1) - Penyuluhan dan Komunikasi Peternakan",
        "fakultas": "FST",
        "jurusan": "Pertanian",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/agribisnis-s1-penyuluhan-dan-komunikasi-peternakan/",
    },
    {
        "nama": "Agribisnis (S1) - Penyuluhan dan Komunikasi Perikanan",
        "fakultas": "FST",
        "jurusan": "Pertanian",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/agribisnis-s1-penyuluhan-dan-komunikasi-perikanan/",
    },
    {
        "nama": "Teknologi Pangan (S1)",
        "fakultas": "FST",
        "jurusan": "Pertanian",
        "jenjang": "S1",
        "url": "https://www.pustaka.ut.ac.id/lib/rbv/fst/ilmu-dan-teknologi-pangan-s1/",
    },
]
