# -*- coding: utf-8 -*-

"""
    calculator_v

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from calculator_v.decorators import lazy_property
from calculator_v.configuration import Configuration
from calculator_v.controllers.simple_calculator_controller import SimpleCalculatorController


class CalculatorVClient(object):

    config = Configuration

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()


