name: snowmobile_conda
channels:
  - conda
  - conda-forge
dependencies:
  - python==3.7
  - pandas>=1.1.5
  - pydantic>=1.7.2
  - appdirs==1.4.4
  - toml>=0.10.1
  - tabulate==0.8.7
  - snowflake-connector-python==2.3.7
  - sqlparse>=0.3.1
#  - ipython>=7.19.0
